[versions]
agp = "8.3.1"
kotlin = "1.9.23"
ksp = "1.9.23-1.0.19"
compose-compiler = "1.5.11"
compose-bom = "2024.03.00"

accompanist = "0.34.0"
appcenter = "5.0.4"
hilt = "2.46.1"
sketch = "3.3.0"
wire = "4.9.3"
lottie = "6.3.0"
media3 = "1.3.0"

compose-destinations = "1.10.2"

androidx-activity = "1.8.2"

lifecycle = "2.7.0"

glide = "4.16.0"
retrofit = "2.9.0"

[plugins]
dependency-analysis = { id = "com.autonomousapps.dependency-analysis", version = "1.29.0" }
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-kapt = { id = "org.jetbrains.kotlin.kapt", version.ref = "kotlin" }
google-ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
kotlin-parcelize = { id = "org.jetbrains.kotlin.plugin.parcelize", version.ref = "kotlin" }
hilt-android = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }
wire = { id = "com.squareup.wire", version.ref = "wire" }

[bundles]

[libraries]

# Compose
compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "compose-bom" }

compose-ui = { group = "androidx.compose.ui", name = "ui" }
compose-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
compose-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
compose-ui-util = { group = "androidx.compose.ui", name = "ui-util" }
compose-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
compose-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
compose-ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }

androidx-test-core = { group = "androidx.test", name = "core", version = "1.5.0" }
androidx-test-rules = { group = "androidx.test", name = "rules", version = "1.5.0" }
androidx-test-runner = { group = "androidx.test", name = "runner", version = "1.5.2" }
androidx-test-ext-junit = { group = "androidx.test.ext", name = "junit", version = "1.1.5" }
androidx-test-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version = "3.5.1" }

wire-runtime = { group = "com.squareup.wire", name = "wire-runtime", version.ref = "wire" }

swiftzer-semver = { group = "net.swiftzer.semver", name = "semver", version = "1.3.0" }

godaddy-color-picker = { group = "com.godaddy.android.colorpicker", name = "compose-color-picker", version = "0.7.0" }

airbnb-lottie = { group = "com.airbnb.android", name = "lottie", version.ref = "lottie" }
airbnb-lottie-compose = { group = "com.airbnb.android", name = "lottie-compose", version.ref = "lottie" }

kotlinx-serialization-json = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version = "1.6.2" }
kotlinx-collections-immutable = { group = "org.jetbrains.kotlinx", name = "kotlinx-collections-immutable", version = "0.3.7" }
kotlinx-coroutines-android = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-android", version = "1.8.0" }

androidx-media3-exoplayer = { group = "androidx.media3", name = "media3-exoplayer", version.ref = "media3" }
androidx-media3-ui = { group = "androidx.media3", name = "media3-ui", version.ref = "media3" }

compose-destinations-core = { group = "io.github.raamcosta.compose-destinations", name = "animations-core", version.ref = "compose-destinations" }
compose-destinations-ksp = { group = "io.github.raamcosta.compose-destinations", name = "ksp", version.ref = "compose-destinations" }

androidx-navigation-compose = { group = "androidx.navigation", name = "navigation-compose", version = "2.7.6" }

hilt-android = { group = "com.google.dagger", name = "hilt-android", version.ref = "hilt" }
hilt-compiler = { group = "com.google.dagger", name = "hilt-compiler", version.ref = "hilt" }

androidx-hilt-navigation-compose = { group = "androidx.hilt", name = "hilt-navigation-compose", version = "1.1.0" }
androidx-hilt-compiler = { group = "androidx.hilt", name = "hilt-android", version = "1.1.0" }

accompanist-drawablepainter = { group = "com.google.accompanist", name = "accompanist-drawablepainter", version.ref = "accompanist" }
# Remove 3
accompanist-insets-ui = { group = "com.google.accompanist", name = "accompanist-insets-ui", version.ref = "accompanist" }
accompanist-systemuicontroller = { group = "com.google.accompanist", name = "accompanist-systemuicontroller", version.ref = "accompanist" }
accompanist-placeholder-material = { group = "com.google.accompanist", name = "accompanist-placeholder-material", version.ref = "accompanist" }


sketch-core = { group = "io.github.panpf.sketch3", name = "sketch-core", version.ref = "sketch" }
sketch-compose = { group = "io.github.panpf.sketch3", name = "sketch-compose", version.ref = "sketch" }
sketch-extensions-compose = { group = "io.github.panpf.sketch3", name = "sketch-extensions-compose", version.ref = "sketch" }
sketch-gif = { group = "io.github.panpf.sketch3", name = "sketch-gif", version.ref = "sketch" }
sketch-okhttp = { group = "io.github.panpf.sketch3", name = "sketch-okhttp", version.ref = "sketch" }

zoomimage-compose-sketch = { group = "io.github.panpf.zoomimage", name = "zoomimage-compose-sketch", version = "1.0.1" }

compose-animation = { group = "androidx.compose.animation", name = "compose-animation" }
animation-graphics = { group = "androidx.compose.animation", name = "animation-graphics" }

compose-material = { group = "androidx.compose.material", name = "material" }
compose-material-icons-core = { group = "androidx.compose.material", name = "material-icons-core" }
compose-material-icons-extended = { group = "androidx.compose.material", name = "material-icons-extended" }

google-material = { group = "com.google.android.material", name = "material", version = "1.11.0" }


androidx-constraintlayout-compose = { group = "androidx.constraintlayout", name = "constraintlayout-compose", version = "1.0.1" }
androidx-constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version = "2.1.4" }

androidx-activity = { group = "androidx.activity", name = "activity-ktx", version.ref = "androidx-activity" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "androidx-activity" }

github-oaid = { group = "com.github.gzu-liyujiang", name = "Android_CN_OAID", version = "4.2.4" }

jetbrains-annotations = { group = "org.jetbrains", name = "annotations", version = "24.1.0" }

androidx-lifecycle-runtime = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycle" }
androidx-lifecycle-viewmodel = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-ktx", version.ref = "lifecycle" }
androidx-lifecycle-viewmodel-compose = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-compose", version.ref = "lifecycle" }

androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version = "1.6.1" }
androidx-annotation = { group = "androidx.annotation", name = "annotation", version = "1.7.1" }
androidx-annotation-experimental = { group = "androidx.annotation", name = "annotation-experimental", version = "1.4.0" }
androidx-collection = { group = "androidx.collection", name = "collection", version = "1.4.0" }

androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version = "1.12.0" }
androidx-core-splashscreen = { group = "androidx.core", name = "core-splashscreen", version = "1.0.1" }

androidx-gridlayout = { group = "androidx.gridlayout", name = "gridlayout", version = "1.0.0" }

androidx-browser = { group = "androidx.browser", name = "browser", version = "1.7.0" }

androidx-palette = { group = "androidx.palette", name = "palette-ktx", version = "1.0.0" }
androidx-window = { group = "androidx.window", name = "window", version = "1.2.0" }
androidx-startup-runtime = { group = "androidx.startup", name = "startup-runtime", version = "1.1.1" }

androidx-datastore-preferences = { group = "androidx.datastore", name = "datastore-preferences", version = "1.0.0" }

glide-core = { group = "com.github.bumptech.glide", name = "glide", version.ref = "glide" }
glide-okhttp3-integration = { group = "com.github.bumptech.glide", name = "okhttp3-integration", version.ref = "glide" }
glide-ksp = { group = "com.github.bumptech.glide", name = "ksp", version.ref = "glide" }

okhttp3-core = { group = "com.squareup.okhttp3", name = "okhttp3-core", version = "4.12.0" }
retrofit2-core = { group = "com.squareup.retrofit2", name = "retrofit", version.ref = "retrofit" }
retrofit2-converter-wire = { group = "com.squareup.retrofit2", name = "converter-wire", version.ref = "retrofit" }

google-gson = { group = "com.google.code.gson", name = "gson", version = "2.10.1" }
litepal = { group = "org.litepal.android", name = "kotlin", version = "3.0.0" }
jaredrummler-colorpicker = { group = "com.jaredrummler", name = "colorpicker", version = "1.1.0" }
matisse = { group = "com.github.lwj1994", name = "Matisse", version = "0.5.3-20220115" }
xxpermissions = { group = "com.github.getActivity", name = "XXPermissions", version = "18.6" }
immersionbar = { group = "com.gyf.immersionbar", name = "immersionbar", version = "3.0.0" }
ucrop = { group = "com.github.yalantis", name = "ucrop", version = "2.2.8" }

butterknife = { group = "com.jakewharton", name = "butterknife", version = "10.2.3" }
butterknife-compiler = { group = "com.jakewharton", name = "butterknife-compiler", version = "10.2.3" }

appcenter-analytics = { group = "com.microsoft.appcenter", name = "appcenter-analytics", version.ref = "appcenter" }
appcenter-crashes = { group = "com.microsoft.appcenter", name = "appcenter-crashes", version.ref = "appcenter" }
appcenter-distribute = { group = "com.microsoft.appcenter", name = "appcenter-distribute", version.ref = "appcenter" }

compose-runtime-tracing = { group = "androidx.compose.runtime", name = "runtime-tracing", version = "1.0.0-beta01" }
junit = { group = "junit", name = "junit", version = "4.13.2" }
